"""p1 baseline

Revision ID: 372f4cd54c3f
Revises:
Create Date: 2026-09-20 23:54:15.322476
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "372f4cd54c3f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("persona_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("profile_dir", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=32), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("geolocation", sa.JSON(), nullable=True),
        sa.Column("viewport", sa.JSON(), nullable=False),
        sa.Column("proxy_config", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("label"),
    )
    op.create_index(op.f("ix_accounts_persona_id"), "accounts", ["persona_id"], unique=False)
    op.create_index(op.f("ix_accounts_status"), "accounts", ["status"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_manifest_hash"), "experiments", ["manifest_hash"], unique=False)
    op.create_index(op.f("ix_experiments_slug"), "experiments", ["slug"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.String(length=32), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.String(length=8), nullable=True),
        sa.Column("default_language", sa.String(length=16), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False)
    op.create_index(op.f("ix_videos_enriched_at"), "videos", ["enriched_at"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("arm", sa.String(length=64), nullable=False),
        sa.Column("repetition", sa.Integer(), nullable=False),
        sa.Column("account_label", sa.String(length=64), nullable=True),
        sa.Column("persona_snapshot", sa.JSON(), nullable=False),
        sa.Column("context_snapshot", sa.JSON(), nullable=False),
        sa.Column("behavior_seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_experiment_id"), "runs", ["experiment_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_kind"), "events", ["kind"], unique=False)
    op.create_index(op.f("ix_events_run_id"), "events", ["run_id"], unique=False)
    op.create_table(
        "steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("active_persona", sa.String(length=64), nullable=True),
        sa.Column("surface", sa.String(length=24), nullable=False),
        sa.Column("source_video_id", sa.String(length=16), nullable=True),
        sa.Column("chosen_video_id", sa.String(length=16), nullable=True),
        sa.Column("chosen_rank", sa.Integer(), nullable=True),
        sa.Column("watched_seconds", sa.Float(), nullable=True),
        sa.Column("watch_fraction", sa.Float(), nullable=True),
        sa.Column("llm_justification", sa.Text(), nullable=True),
        sa.Column("llm_usage", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "index", name="uq_step_run_index"),
    )
    op.create_index(op.f("ix_steps_chosen_video_id"), "steps", ["chosen_video_id"], unique=False)
    op.create_index(op.f("ix_steps_run_id"), "steps", ["run_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=16), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("channel_name", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.String(length=32), nullable=True),
        sa.Column("badge", sa.String(length=64), nullable=True),
        sa.Column("was_chosen", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_id", "rank", name="uq_observation_step_rank"),
    )
    op.create_index(op.f("ix_observations_step_id"), "observations", ["step_id"], unique=False)
    op.create_index(op.f("ix_observations_video_id"), "observations", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_video_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_step_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_steps_run_id"), table_name="steps")
    op.drop_index(op.f("ix_steps_chosen_video_id"), table_name="steps")
    op.drop_table("steps")
    op.drop_index(op.f("ix_events_run_id"), table_name="events")
    op.drop_index(op.f("ix_events_kind"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_experiment_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_videos_enriched_at"), table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_experiments_slug"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_manifest_hash"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_accounts_status"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_persona_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
